### ISSUE TITLE
Tracker: Gazebo9 9.15.0 release

### ISSUE THREAD

**Issue by j-rivero** [gazebo-tooling/release-tools#298]
There are some problems affecting different platforms in gazebo9 release:

**Legend** :green_circle: in the repo :yellow_circle: waiting in/for the buildfarm :red_circle: requires action :black_circle: does not apply

 * **Ubuntu amd64 platforms:**
   * :green_circle: Focal/amd64
   * :green_circle: Bionic/amd64: 9.15.1-2
   * :green_circle: Xenial/amd64: 9.15.1-3 

 * **Ubuntu ARM platforms:**
   * :green_circle: Focal/arm64
   * :green_circle: Bionic/arm64
   * :red_circle: Bionic/armhf:
     * [x] [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo9-debbuilder&build=649)](https://build.osrfoundation.org/job/gazebo9-debbuilder/649/) linking problems with SingletonT class.
   * :black_circle: Xenial/arm64: no release ever
   * :black_circle: Focal/armhf: no release ever
   * :black_circle: Xenial/armhf: no release ever

 * **Ubuntu i386 platforms:**
   * :green_circle: Bionic/i386: 9.15.1-2
   * :green_circle: Xenial/i386: 9.15.1-3 

 * **Debian amd64 platforms:**
   * :green_circle: Stretch/amd64:
   * :black_circle: Sid/amd64:
     * [x] Sid is unsupported, gazebo11 is the current version https://github.com/ignition-release/gazebo9-release/pull/7 

 * **Debian ARM platforms:**
   * :red_circle: Stretch/arm64
        * [x] needs fuel-tools-dev [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-fuel-tools-debbuilder&build=100)](https://build.osrfoundation.org/view/All/job/ign-fuel-tools-debbuilder/100/)
   * :black_circle: Sid/*:
     * [x] Sid is unsupported, gazebo11 is the current version https://github.com/ignition-release/gazebo9-release/pull/7 
   * :black_circle: Stretch/armhf
        * no fuel-tools/common1 release. Last gazebo is 9.7.0. Not releasing anymore.

* **Brew**
  * :green_circle: : Bottles
       * [x] [pending merge](https://github.com/osrf/homebrew-simulation/pull/1168)

**Comment by j-rivero** [comment]
Added the restrictions to the non available platforms, the total of builds for gazebo9 releases is 8 for Debian/Ubuntu. The main platforms still lack of releases for getting the -3 revision.

**Comment by j-rivero** [comment]
FYI: Xenial is EOL. My intention is not to create new versions for Xenial, latest one could be 9.18.0
