### ISSUE TITLE
Release Garden

### ISSUE THREAD

**Issue by chapulina** [gazebo-tooling/release-tools#578]
## Timeline

Current tentative timeline

* ~~Feature freeze: 2022/07/29 (Friday)~~
* ~~Code freeze: 2022/08/31 (Wednesday)~~
* ~~Tutorial party: 2022/09/01 (Thu) ~ 2022/09/16 (Fri)~~
* ~~Internal QA: 2022/09/19 (Mon) ~ 2022/09/23 (Fri)~~
* ~~Community meeting: 2022/09/28 (Wednesday)~~
* ~~Announcement: 2022/10/03 (Monday)~~

## During development

- [x] Bump major version of libraries early in the development cycle (use [bump_libraries](bump_libraries.md) template).
- [x] Work with artist on logo.

## Feature freeze

- [x] Choose name for next release.
- [x] Merge each library forward from previous versions
    - [x] `gz-cmake`
    - [x] `gz-common`
    - [x] `gz-fuel-tools` (there are open bug fixes that need to be ported by code freeze)
    - [x] `gz-sim`
        - https://github.com/gazebosim/gz-sim/pull/1626
        - https://github.com/gazebosim/gz-sim/pull/1630
        - https://github.com/gazebosim/gz-sim/pull/1631
        - https://github.com/gazebosim/gz-sim/pull/1633
    - [x] `gz-gui` - https://github.com/gazebosim/gz-gui/pull/446
    - [x] `gz-launch` - https://github.com/gazebosim/gz-launch/pull/186
    - [x] `gz-math`
    - [x] `gz-msgs` - https://github.com/gazebosim/gz-msgs/pull/289
    - [x] `gz-physics` - https://github.com/gazebosim/gz-physics/pull/398
    - [x] `gz-plugin` - https://github.com/gazebosim/gz-plugin/pull/98
    - [x] `gz-rendering`
    - [x] `gz-sensors`
      - https://github.com/gazebosim/gz-sensors/pull/252
      - https://github.com/gazebosim/gz-sensors/pull/247
    - [x] `gz-tools`
    - [x] `gz-transport` - https://github.com/gazebosim/gz-transport/pull/343
    - [x] `gz-utils` - https://github.com/gazebosim/gz-utils/pull/75
    - [x] `sdformat` - https://github.com/gazebosim/sdformat/pull/1103
- [x] Create stable branches off of `main`
    - [x] Make sure the new branches are covered by branch protection
    - [x] `gz-cmake3`
    - [x] `gz-tools2`
    - [x] `gz-common5`
    - [x] `gz-fuel-tools8`
    - [x] `gz-sim7`
    - [x] `gz-gui7`
    - [x] `gz-launch6`
    - [x] `gz-math7`
    - [x] `gz-msgs9`
    - [x] `gz-physics6`
    - [x] `gz-plugin2`
    - [x] `gz-rendering7`
    - [x] `gz-sensors7`
    - [x] `gz-transport12`
    - [x] `gz-utils2`
    - [x] `sdf13`
- [x] Pull requests previously targeted at `main`:
    - Bug fixes:
       - Retarget to the new stable branch.
       - Label with [beta](https://github.com/search?q=org%3Agazebosim+label%3Abeta&state=open)
       - They can be merged until code freeze.
    - Backwards-compatible features, either:
       - Retarget them to the new stable branch (but they can only be merged after the stable release), or
       - Keep targeting `main` and backport after the stable release.
    - Breaking features:
       - Keep targeting `main` (i.e. they will be delayed until the next major release)
- [x] Bump all `main` branches to the next major version (`X.0.0~pre1`)
    - [x] Source code ([example](https://github.com/gazebosim/gz-common/pull/193))
        * https://github.com/gazebosim/gz-cmake/pull/296
        * https://github.com/gazebosim/gz-tools/pull/102
        * https://github.com/gazebosim/gz-common/pull/412
        * https://github.com/gazebosim/gz-fuel-tools/pull/283
        * https://github.com/gazebosim/gz-sim/pull/1640
        * https://github.com/gazebosim/gz-gui/pull/456
        * https://github.com/gazebosim/gz-launch/pull/189
        * https://github.com/gazebosim/gz-math/pull/478
        * https://github.com/gazebosim/gz-msgs/pull/292
        * https://github.com/gazebosim/gz-physics/pull/399
        * https://github.com/gazebosim/gz-plugin/pull/99
        * https://github.com/gazebosim/gz-rendering/pull/699
        * https://github.com/gazebosim/gz-sensors/pull/254
        * https://github.com/gazebosim/gz-transport/pull/344
        * https://github.com/gazebosim/gz-utils/pull/76
        * https://github.com/gazebosim/sdformat/pull/1104
    - [x] Add files to `gazebodistro` ([example](https://github.com/gazebo-tooling/gazebodistro/pull/12))
        * https://github.com/gazebo-tooling/gazebodistro/pull/116
        * https://github.com/gazebo-tooling/gazebodistro/pull/115
        * https://github.com/gazebo-tooling/gazebodistro/pull/119
        * https://github.com/gazebo-tooling/gazebodistro/pull/120
    - [x] Add aliases to `homebrew-simulation` ([example](https://github.com/osrf/homebrew-simulation/commit/1f8602af6f52e06e0542eebfbdbe97f5f6cf950c))
        * https://github.com/osrf/homebrew-simulation/pull/1981
        * https://github.com/osrf/homebrew-simulation/pull/1985
        * https://github.com/osrf/homebrew-simulation/pull/1986
        * https://github.com/osrf/homebrew-simulation/pull/1988
    - [x] Create new `-release` repositories (use [this script](https://github.com/gazebo-tooling/release-tools/blob/master/release-repo-scripts/new_ignition_release_repos.bash))
    - [x] Enable nightlies for all `main` branches on `gzdev` ([example](https://github.com/gazebo-tooling/gzdev/pull/50))
        - https://github.com/gazebo-tooling/gzdev/pull/62
    - [x] Build nightlies from new stable branches
        - https://github.com/gazebo-tooling/release-tools/pull/785
        - https://github.com/gazebo-tooling/release-tools/pull/790
    - [x] Execute the tick-tock's "tock" for deprecations ([example](https://github.com/gazebosim/gz-sim/pull/875))
        * 
- [x] Pre-release libraries as all `beta` labels are merged.
    - [x] `gz-cmake3`
    - [x] `gz-tools2`
    - [x] `gz-common5`
    - [x] `gz-fuel-tools8`
    - [x] `gz-sim7`
    - [x] `gz-gui7`
    - [x] `gz-launch6`
    - [x] `gz-math7`
    - [x] `gz-msgs9`
    - [x] `gz-physics6`
    - [x] `gz-plugin2`
    - [x] `gz-rendering7`
    - [x] `gz-sensors7`
    - [x] `gz-transport12`
    - [x] `gz-utils2`
    - [x] `sdf13`
- [x] Make collection pre-release after all libraries are pre-released.
- [x] Update public documentation to install from pre-releases instead of nightlies.
    - https://github.com/gazebosim/docs/pull/292

## Code freeze

- [x] Start T-Shirt campaign
    - https://community.gazebosim.org/t/gazebo-garden-tshirts-available/1575
- [x] Hold tutorial party ([example](https://community.gazebosim.org/t/ignition-edifice-tutorial-party-support-open-source-and-get-t-shirts/866))
- [x] PRs fixing documentation and critical bugs can be merged and pre-released
- [x] Library changelogs
    - [x] `gz-cmake3` https://github.com/gazebosim/gz-cmake/pull/310
    - [x] `gz-tools2` https://github.com/gazebosim/gz-tools/pull/112
    - [x] `gz-common5` https://github.com/gazebosim/gz-common/pull/443
    - [x] `gz-fuel-tools8` https://github.com/gazebosim/gz-fuel-tools/pull/301
    - [x] `gz-gui7` https://github.com/gazebosim/gz-gui/pull/492
    - [x] `gz-launch6` https://github.com/gazebosim/gz-launch/pull/201
    - [x] `gz-math7` https://github.com/gazebosim/gz-math/pull/506
    - [x] `gz-msgs9` https://github.com/gazebosim/gz-msgs/pull/305
    - [x] `gz-physics6` https://github.com/gazebosim/gz-physics/pull/427
    - [x] `gz-plugin2` https://github.com/gazebosim/gz-plugin/pull/107
    - [x] `gz-rendering7` https://github.com/gazebosim/gz-rendering/pull/728
    - [x] `gz-sensors7` https://github.com/gazebosim/gz-sensors/pull/274
    - [x] `gz-sim7` https://github.com/gazebosim/gz-sim/pull/1729
    - [x] `gz-transport12` https://github.com/gazebosim/gz-transport/pull/361
    - [x] `gz-utils2` https://github.com/gazebosim/gz-utils/pull/79
    - [x] `sdf13` https://github.com/gazebosim/sdformat/pull/1139
- [x] Make stable releases
    - [x] `gz-cmake3`
    - [x] `gz-tools2`
    - [x] `gz-common5`
    - [x] `gz-fuel-tools8`
    - [x] `gz-gui7`
      - [ ] Fix arm releases.
    - [x] `gz-launch6`
    - [x] `gz-math7`
    - [x] `gz-msgs9`
    - [x] `gz-physics6`
        - [ ] Fix arm releases.
    - [x] `gz-plugin2`
    - [x] `gz-rendering7`
      - [ ] Fix arm releases.
    - [x] `gz-sensors7`
       - [ ] Fix arm releases.
    - [x] `gz-sim7`
    - [x] `gz-transport12`
    - [x] `gz-utils2`
    - [x] `sdf13`

## Release day

- [x] Make collection stable release after all libraries are released.
- [x] Update `gazebodistro` ([example](https://github.com/gazebo-tooling/gazebodistro/pull/31))
- [x] Make GitHub releases for all the X.0.0 versions ([example](https://github.com/gazebosim/gz-transport/releases/tag/ignition-transport9_9.0.0))
- [x] Update docs to say release is stable ([example](https://github.com/ignitionrobotics/docs/pull/171))
- [x] Make announcement

## Post-release

- [x] Enable Jenkins CI for new stable branches ([example](https://github.com/ignition-tooling/release-tools/pull/299))
- [x] Remove nightlies for release branches on `gzdev` ([example](https://github.com/ignition-tooling/gzdev/pull/19)) https://github.com/gazebo-tooling/gzdev/pull/64
- [x] Update all repositories to default to the new stable branches.

If the collection will be officially paired with a ROS 2 distro:

- [ ] Update REP-2000 when ROS 2 distro is added ([example](https://github.com/ros-infrastructure/rep/pull/291))
- [ ] Import stable releases into https://packages.ros.org ([example](https://github.com/ros-infrastructure/reprepro-updater/pull/109))
- [ ] Add new rosdep keys ([example](https://github.com/ros/rosdistro/pull/29176))
- [ ] Bloom-release `ros_ign` with the new version into Rolling before fork ([example](https://github.com/ros/rosdistro/pull/29192))

# Status tracker

Track stable release of metapackage `gz-<collection>`.

* :hourglass: TODO
* :yellow_circle: waiting in the buildfarm
* :green_circle: in the repo
* :red_circle: requires action
* :black_circle: no release

### Linux

 * **Ubuntu:**
   - [x] :green_circle: : Focal/amd64
   - [x] :green_circle: Jammy/amd64
   - [x] :green_circle: : Focal/arm64
   - [x] :green_circle: Focal/armhf
   - [x] :green_circle: Jammy/arm64
   - [ ] :red_circle: Jammy/armhf
     - Blocked by  [ogre-next-2.3 fails to compile](https://build.osrfoundation.org/job/ogre-2.3-debbuilder/41/consoleFull#506379416ea37b8d-a6d4-40ae-8431-d90c018842af)

 * **Debian:**
   - :black_circle: None in this release.

### macOS

* **Brew**
  - [x] :green_circle: Bottles BigSur
  - [x] :green_circle: Bottles Carolina

### Windows

:warning:  Please note that gz Garden on Windows is not fully functional and won't work out of the box. Please read the [open issue for Windows ](https://github.com/gazebosim/gz-sim/issues/168) support for more information.

* **Conda-forge** (community effort)
  - [x] :green_circle: https://github.com/conda-forge/libignition-cmake0-feedstock/issues/26 (thanks mainly to @traversaro)

**Comment by scpeters** [comment]
our nightly builds are still set to build from `main`, and bumping the major version numbers on `main` has broken some nightly builds:

[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-math7-debbuilder&build=802)](https://build.osrfoundation.org/view/ign-garden/job/ign-math7-debbuilder/802/) https://build.osrfoundation.org/view/ign-garden/job/ign-math7-debbuilder/802/

I propose updating the nightly builds to use release branches: https://github.com/gazebo-tooling/release-tools/pull/785

**Comment by scpeters** [comment]
> our nightly builds are still set to build from `main`, and bumping the major version numbers on `main` has broken some nightly builds:
> 
> [![Build Status](https://camo.githubusercontent.com/ef12cc26b63eadbab6d47af23b2fce7d17db9925f761b9ab99fdc7e3ed62302a/68747470733a2f2f6275696c642e6f7372666f756e646174696f6e2e6f72672f6275696c645374617475732f69636f6e3f6a6f623d69676e2d6d617468372d6465626275696c646572266275696c643d383032)](https://build.osrfoundation.org/view/ign-garden/job/ign-math7-debbuilder/802/) https://build.osrfoundation.org/view/ign-garden/job/ign-math7-debbuilder/802/
> 
> I propose updating the nightly builds to use release branches: #785

we'll also need to update the branches in the unreleased homebrew formulae and in gzdev

**Comment by chapulina** [comment]
> we'll also need to update the branches in the unreleased homebrew formulae and in gzdev (gzdev is based on cmake project name, not branch name, so it doesn't need any changes)

* https://github.com/osrf/homebrew-simulation/pull/1985
* https://github.com/gazebo-tooling/gzdev/pull/62

**Comment by scpeters** [comment]
the gz-gui7 and gz-sim7 debbuilder jobs are still unstable. I think https://github.com/gazebo-release/gz-sim7-release/pull/15 will fix gz-sim7, but I don't see a PR yet to fix [gz-gui7-release](https://github.com/gazebo-release/gz-gui7-release)

**Comment by azeey** [comment]
> the gz-gui7 and gz-sim7 debbuilder jobs are still unstable. I think [gazebo-release/gz-sim7-release#15](https://github.com/gazebo-release/gz-sim7-release/pull/15) will fix gz-sim7, but I don't see a PR yet to fix [gz-gui7-release](https://github.com/gazebo-release/gz-gui7-release)

https://github.com/gazebo-release/gz-gui7-release/pull/13

**Comment by scpeters** [comment]
gz-tools 2.0.0 Jammy arm64 debbuild failed: https://github.com/gazebosim/gz-tools/issues/114
