### ISSUE TITLE
Tracker: new EC2 Windows agents issues

### ISSUE THREAD

**Issue by j-rivero** [gazebo-tooling/release-tools#892]
Tracker for the existing issues and works related to the EC2 Windows agents. Most problems come from the bump of MSVC to 2022 and the enable of DART from vcpkg (which brings to the builds other vcpkg dependencies like urdfdom or ode).

* [x] https://github.com/osrf/vcpkg-ports/pull/10
* [x] https://github.com/osrf/vcpkg-ports/pull/9
* [ ] https://github.com/gazebosim/sdformat/pull/1259
* [ ] Port https://github.com/gazebosim/sdformat/pull/1259 to sdf12 (branch exists).

New compilation warnings and test errors:
 * [ ] https://github.com/gazebosim/gz-math/issues/527
 * [ ] gz-sim7 [PhysicsSystemFixtureWithDart6_10 failing tests]( https://build.osrfoundation.org/job/_test_ign_gazebo-gz-sim7-win/22/testReport/)
 * [ ] gz-physics6 [test falures](https://build.osrfoundation.org/job/_test_ign_physics-gz-6-win/3/)

**Comment by Crola1702** [comment]
- [ ] [gz-launch4 -win](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/49/) warnings (Same warning as https://github.com/gazebosim/gz-math/issues/527)
- [ ] [Gz-transport8-win](https://build.osrfoundation.org/job/ign_transport-ign-8-win/57/) warnings (Same warning as https://github.com/gazebosim/gz-math/issues/527)

**Comment by j-rivero** [comment]
Affected by https://github.com/gazebo-tooling/release-tools/issues/901

**Comment by j-rivero** [comment]
If I change back to use VS19 without dart, I've managed to stabilize the results to the same than in current situation:

 * gz-sim7 [![Build Status](https://build.osrfoundation.org/job/_test_ign_gazebo-gz-sim7-win/52/badge/icon)](https://build.osrfoundation.org/job/_test_ign_gazebo-gz-sim7-win/52/)
 * gz-physics6 [![Build Status](https://build.osrfoundation.org/job/_test_ign_physics-gz-6-win/18/badge/icon)](https://build.osrfoundation.org/job/_test_ign_physics-gz-6-win/18/)
 * gz-gazebo6: [![Build Status](https://build.osrfoundation.org/job/_test_ign_gazebo-ign-6-win/10/badge/icon)](https://build.osrfoundation.org/job/_test_ign_gazebo-ign-6-win/10/)

We are going with this option to execute the first step of the migration.

**Comment by j-rivero** [comment]
Some work on supporting multiple compilers https://github.com/gazebo-tooling/release-tools/pull/911
