### ISSUE TITLE
Support for releasing ros_gzgarden unofficial packages for Humble

### ISSUE THREAD

**Issue by j-rivero** [gazebo-tooling/release-tools#895]
## Motivation

Gz Garden [is not currently supported by binaries in any ROS 2 distribution](https://gazebosim.org/docs/garden/ros_installation#gazebo-garden-not-recommended-) although the `ros_gz` bridge supports from source compilations using Gz Garden for different ROS 2 distributions. Building from source is the recommended way for advanced users that really want to use Garden on ROS 2 Humble or ROS 2 Rolling.

For Gazebo Classic with its 11 version and ROS 1 in this situation where the official version was an older version of Gazebo,  we generated years ago **unofficial** packages named `gazebo11_ros_pkgs` hosted in `packages.osrfoundation.org` that could be used to [install Gazebo11 instead of Gazebo9 on Melodic and others](https://classic.gazebosim.org/tutorials?tut=ros_wrapper_versions&cat=connect_ros#Gazebo11.xseries). 

In this case, we can try to generate **unofficial** packages for the users of Gazebo 
Garden + ROS 2 Humble that could help the advanced user with their installations. 

## Roadmap:

 * [x] Support for rosdep to rename Gz Fortress to Gz Garden
    * https://github.com/osrf/osrf-rosdep/pull/12 
    * https://github.com/osrf/osrf-rosdep/pull/13
 * [x] Jenkins DSL support for debbuilders of ros_gz
    * https://github.com/gazebo-tooling/release-tools/pull/896 
    * https://github.com/gazebo-tooling/release-tools/pull/897
 * [x] Scripts to support forking ros-gbp2 release, setup the fork and releasing operations
    * https://github.com/gazebo-tooling/release-tools/pull/898
    * https://github.com/gazebo-tooling/release-tools/pull/926
    * https://github.com/gazebo-tooling/release-tools/pull/927
 * [x] Release a test version into the prerelease repository
 * [x] Create the final fork repository in GitHub osrf
   * https://github.com/gazebo-release/ros_ign-release 
 * [x] Release into stable from the fork repository
   * Tested https://build.osrfoundation.org/job/ros_gz_bridge-install-pkg_unofficial-any-manual/43/ 
 * [x] Periodic smoke test to detect possible ABI breakages if ROS official packages make any ABI incompatible change 
   *  https://github.com/gazebo-tooling/release-tools/pull/950 
   *  https://github.com/gazebo-tooling/release-tools/pull/956

## Testing:

 * Install the [Gazebo prerelease](https://classic.gazebosim.org/tutorials?tut=install_unstable&cat=install#Gazeboprereleaserepo) repository
 * `apt-get update && apt-get install ros-humble-ros-gzgarden` (will uninstall Humble official packages if they are installed)

**Comment by j-rivero** [comment]
Quick test using the demos package:
![image](https://user-images.githubusercontent.com/2098802/228595553-3615bd55-5779-4b4e-9896-e47f8f8ce895.png)

**Comment by azeey** [comment]
I had mixed results when testing this. I tried running `ros2 run ros_gz_bridge parameter_bridge /chatter@std_msgs/msg/String@ignition.msgs.StringMsg` and it worked, but not `ros2 run ros_gz_bridge parameter_bridge /chatter@std_msgs/msg/String@gz.msgs.StringMsg` (with `gz` instead of `ignition`). I also didn't see the `GZ_VERSION` environment variable set in the [build logs](https://build.osrfoundation.org/job/ros-gz-bridge-bloom-debbuilder/9/consoleFull)

**Comment by j-rivero** [comment]
> I also didn't see the `GZ_VERSION` environment variable set in the [build logs](https://build.osrfoundation.org/job/ros-gz-bridge-bloom-debbuilder/9/consoleFull)

About this one. I tried to pass environment variables to bloom, but this is not a use case supported. Instead of that, I'm injecting the variable to the rules file, see [these lines from the open PR](https://github.com/gazebo-tooling/release-tools/pull/898/files#diff-df88e2ffb65fa6e340ce0fc7d559a4932cb15e7d92d1ef0649b2d65b2544c25eR34-R41).

**Comment by j-rivero** [comment]
> I had mixed results when testing this. I tried running `ros2 run ros_gz_bridge parameter_bridge /chatter@std_msgs/msg/String@ignition.msgs.StringMsg` and it worked, but not `ros2 run ros_gz_bridge parameter_bridge /chatter@std_msgs/msg/String@gz.msgs.StringMsg` (with `gz` instead of `ignition`).

I have uploaded new `0.244.10-1002` versions. Could you please give it another try when you have time?

**Comment by bperseghetti** [comment]
> > I had mixed results when testing this. I tried running `ros2 run ros_gz_bridge parameter_bridge /chatter@std_msgs/msg/String@ignition.msgs.StringMsg` and it worked, but not `ros2 run ros_gz_bridge parameter_bridge /chatter@std_msgs/msg/String@gz.msgs.StringMsg` (with `gz` instead of `ignition`).
> 
> I have uploaded new `0.244.10-1002` versions. Could you please give it another try when you have time?
> 
> FYI @bperseghetti

Thanks!
Will give it a shot. If this works, it would also be great for Iron.

**Comment by bperseghetti** [comment]
Hey @j-rivero, I was testing the new package and noticed that `ros-humble-ros-gzgarden-sim-demos` has dependencies that install ign. I was discussing with @azeey about us possibly removing `ros-humble-ros-gzgarden-sim-demos` from `ros-humble-ros-gzgarden` package dependencies. Currently:

```bash
Package: ros-humble-ros-gzgarden
Version: 0.244.10-1002jammy
Architecture: amd64
Maintainer: Louise Poubel <louise@openrobotics.org>
Installed-Size: 43
Depends: ros-humble-ros-gzgarden-bridge, ros-humble-ros-gzgarden-image, ros-humble-ros-gzgarden-sim, ros-humble-ros-gzgarden-sim-demos, ros-humble-ros-workspace
Conflicts: ros-humble-ros-gz
.......
```
Ideally:
```bash
Package: ros-humble-ros-gzgarden
Version: 0.244.10-1002jammy
Architecture: amd64
Maintainer: Louise Poubel <louise@openrobotics.org>
Installed-Size: 43
Depends: ros-humble-ros-gzgarden-bridge, ros-humble-ros-gzgarden-image, ros-humble-ros-gzgarden-sim, ros-humble-ros-workspace
Conflicts: ros-humble-ros-gz
.......
```

**Comment by bperseghetti** [comment]
Everything though is working for me so far:
![image](https://github.com/gazebo-tooling/release-tools/assets/10233412/d82863a5-f8d9-43cb-aa50-a85cd9382d6b)

**Comment by bperseghetti** [comment]
I guess I still will need to test the portion for spawning entities in sim, but if that works fine the rest should all bee good too I think.

**Comment by j-rivero** [comment]
> I had mixed results when testing this. I tried running `ros2 run ros_gz_bridge parameter_bridge /chatter@std_msgs/msg/String@ignition.msgs.StringMsg` and it worked, but not `ros2 run ros_gz_bridge parameter_bridge /chatter@std_msgs/msg/String@gz.msgs.StringMsg`

I think that knows what could be going on. Be sure of using `gz` cli instead of `ign` cli and that can make both `ignition.msgs` (with a warning that really using gz.msgs) and `gz.msgs` namespaces to woth.

**Comment by azeey** [comment]
> > I had mixed results when testing this. I tried running `ros2 run ros_gz_bridge parameter_bridge /chatter@std_msgs/msg/String@ignition.msgs.StringMsg` and it worked, but not `ros2 run ros_gz_bridge parameter_bridge /chatter@std_msgs/msg/String@gz.msgs.StringMsg`
> 
> I think that knows what could be going on. Be sure of using `gz` cli instead of `ign` cli and that can make both `ignition.msgs` (with a warning that really using gz.msgs) and `gz.msgs` namespaces to work.

Ah, thanks! I might have used `ign` by mistake. Using `gz` seems to work well!

**Comment by bperseghetti** [comment]
@azeey @j-rivero Interestingly it seems like this did not bring in the actuator msgs update for ros_gz_bridge. Could it be run again? Maybe the extra dependencies were not installed and then left out?

Test it with:
```bash
ros2 topic pub -r 10 /actuators actuator_msgs/msg/Actuators "{velocity: [1, 1, 1, 1]}"
```
followed by:
```bash
ros2 run ros_gz_bridge parameter_bridge /actuators@actuator_msgs/msg/Actuators]gz.msgs.Actuators
```

Currently it results in:
```bash
[INFO] [1684680469.220630653] [ros_gz_bridge]: Creating ROS->GZ Bridge: [/actuators (actuator_msgs/msg/Actuators) -> /actuators (gz.msgs.Actuators)] (Lazy 0)
[WARN] [1684680469.221955939] [ros_gz_bridge]: Failed to create a bridge for topic [/actuators] with ROS2 type [actuator_msgs/msg/Actuators] to topic [/actuators] with Gazebo Transport type [gz.msgs.Actuators]
```

**Comment by j-rivero** [comment]
> @azeey @j-rivero Interestingly it seems like this did not bring in the actuator msgs update for ros_gz_bridge. Could it be run again? Maybe the extra dependencies were not installed and then left out?

Should not be the case. Did the humble version of `ros_gz` released the actuators code? I don't see it in the [humble branch](https://github.com/gazebosim/ros_gz/tree/humble/ros_gz_bridge/src/convert) but see it in the `ros2` (rolling) branch.

**Comment by azeey** [comment]
I think https://github.com/gazebosim/ros_gz/pull/378 needs to be backported to the humble branch.

**Comment by bperseghetti** [comment]
@j-rivero Ah, yep, my bad on that. So used to thinking of the ros2 branch as the used for humble. Does the ROS2 branch work for Iron?
Since it's only a day away any chance we could do a pre-release for iron based on ros2 branch?

**Comment by bperseghetti** [comment]
Wait, how would this work with gz::msgs instead of ignition::msgs if it's on humble branch instead of being built from ros2 branch?

**Comment by bperseghetti** [comment]
@azeey @j-rivero Think this PR should do it: https://github.com/gazebosim/ros_gz/pull/394

**Comment by j-rivero** [comment]
> @azeey @j-rivero Think this PR should do it: [gazebosim/ros_gz#394](https://github.com/gazebosim/ros_gz/pull/394)

Great, that is merged. We need a new release of for Humble from the `ros_gz` packages into the ros repo and I can use it to release from there.

**Comment by j-rivero** [comment]
Released into the stable repository version `0.244.11-1002` . Tested [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ros_gz_bridge-install-pkg_unofficial-any-manual&build=43)](https://build.osrfoundation.org/job/ros_gz_bridge-install-pkg_unofficial-any-manual/43/)
