### ISSUE TITLE
Support for releasing ros_gzgarden unofficial packages for Iron

### ISSUE THREAD

**Issue by bperseghetti** [gazebo-tooling/release-tools#945]
## Motivation
Same as #895 but for Iron. @azeey @j-rivero 

## Roadmap (edited by @j-rivero):
 - [x]  Support for rosdep to rename Gz Fortress to Gz Garden
   - https://github.com/osrf/osrf-rosdep/pull/14 
 - [x] Parametrize tooling in release-tools to support different ROS 2 versions
   - https://github.com/gazebo-tooling/release-tools/pull/958
 - [x] Release a test version into the prerelease repository using fork -release repo
 - [x] Use j-rivero fork to generate metadata and to create the prerelease from it
 - [x] Test in the buildfarm using the manual-any job
   - [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ros_gz_bridge-install-pkg_unofficial-any-manual&build=48)](https://build.osrfoundation.org/job/ros_gz_bridge-install-pkg_unofficial-any-manual/48/) 
 - [x] Create the track for iron in the ros_ign-release (can be autogenerated by bloom?)
 - [x] Push info to gazebo-release/ros_ign-release repository
 - [x] Release into stable from the ros_ign-release repository
 - [x] DSL support for testing Iron GzGarden
   - https://github.com/gazebo-tooling/release-tools/pull/960
 
## Testing:
Install the [Gazebo prerelease](https://classic.gazebosim.org/tutorials?tut=install_unstable&cat=install#Gazeboprereleaserepo) repository
apt-get update && apt-get install ros-iron-ros-gzgarden (will uninstall Iron official packages if they are installed)

**Comment by j-rivero** [comment]
Iron packages are in the prerelease repository. Ready for testing.

**Comment by bperseghetti** [comment]
Should be able to test it starting this week!

**Comment by j-rivero** [comment]
Stable release is out.
