### ISSUE TITLE
Replace tarball generation in release.py by a Jenkins job

### ISSUE THREAD

**Issue by j-rivero** [gazebo-tooling/release-tools#990]
Members of the Gazebo core team currently need to push files to S3 during the release process for Gazebo packages (including sdformat) using personal S3 credentials. The upload is handled using the `release.py` script. Moving this process into a centralized automation system will support growing the Gazebo core team without requiring the granting of S3 bucket access to more individuals and remove the need for existing personal credentials.

**Implementation:**
Spawn a generation job in Jenkins from release.py, which will create the source tarball and push it to S3 and/or GitHub Releases, it could potentially also create the Debian source package and trigger the release upload for the source package only. Then on success, trigger the numerous parameterized debbuilder jobs. The release.py job could either block until the “source release” job is complete or just exit once it is triggered and rely on Jenkins to notify the releaser that their triggered “source builder” or one of the subsequently triggered debbuilder jobs failed.

**Roadmap**:
 - [x] Implement the tarball generation Jenkins job https://github.com/gazebo-tooling/release-tools/pull/989
 - [x] Implement a Jenkins job to call release.py https://github.com/gazebo-tooling/release-tools/pull/988
 - [x] Draft the job chain in Jenkins that involves tarball creation + repository_uploader + release.py  https://github.com/gazebo-tooling/release-tools/commit/91c57f16924d9236a3a4bdc1e952bac7295c4c7c
 - [x] Implement the job chain in DSL
   - [x] https://github.com/gazebo-tooling/release-tools/pull/988
   - [x] https://github.com/gazebo-tooling/release-tools/pull/989
   - [x] https://github.com/gazebo-tooling/release-tools/pull/1008
   - [x] https://github.com/gazebo-tooling/release-tools/pull/1024
   - [x] https://github.com/gazebo-tooling/release-tools/pull/1033 
   - [x] https://github.com/gazebo-tooling/release-tools/pull/1035
   - [x] https://github.com/gazebo-tooling/release-tools/pull/1036
   - [x] https://github.com/gazebo-tooling/release-tools/pull/1046
 - [ ] Prepare release.py to remove tarball generation
   - [x] https://github.com/gazebo-tooling/release-tools/pull/1014
   - [x] https://github.com/gazebo-tooling/release-tools/pull/1025
   - [ ] https://github.com/gazebo-tooling/release-tools/pull/1048
 - [x] Prepare packages uploader to support tarball names 
   - [x] https://github.com/gazebo-tooling/release-tools/pull/1006
 - [x] Update documentation
   - [x] https://github.com/gazebosim/docs/pull/403

**Comment by scpeters** [comment]
https://github.com/gazebo-tooling/release-tools/issues/1020 is kind of related

**Comment by j-rivero** [comment]
All merged.
