### ISSUE TITLE
Support for releasing ros_gzharmonic unofficial packages for Humble/Iron

### ISSUE THREAD

**Issue by j-rivero** [gazebo-tooling/release-tools#994]
## Motivation
Same as #895 but changing Garden by Harmonic and supporting ROS 2 Iron/Humble. 

## Roadmap:
 - [x] Support for rosdep to rename Gz Fortress to Gz Harmonic
   - [x] Harmonic keys https://github.com/osrf/osrf-rosdep/pull/15
   - [x] For ROS 2 Humble/Iron https://github.com/osrf/osrf-rosdep/pull/16
 - [x] Check tooling in release-tools to support different Gz versions than Garden
   - [x] https://github.com/gazebo-tooling/release-tools/pull/999
   - [x] https://github.com/gazebo-tooling/release-tools/pull/1003
 - [x] Use j-rivero fork to generate metadata and to create the prerelease from it
        https://github.com/j-rivero/ros_ign-gzharmonic-release
   - ~~For ROS 2 Humble~~ not supported in `ros2` branch
   - [x] For ROS 2 Iron
 - [x] Release a test version into the prerelease repository using fork -release repo
   - [x]  need a new ros_gz release: done 0.246.0 on `ros2` branch
   - ~~For ROS 2 Humble~~ not supported in `ros2` branch
   - [x] For ROS 2 Iron: `ros-iron-ros-gzharmonic-*` packages are ready in prerelease.
 - [x] Test in the buildfarm using the manual-any job
   - https://build.osrfoundation.org/job/ros_gz_bridge-install-pkg_unofficial-any-manual/55/

After stable release:

 - [x] Create an official ros_ign-gzharmonic-release repository
   - Created https://github.com/gazebo-release/ros_gz-gzharmonic-release 
 - [x] Repeat the [process](https://github.com/gazebo-tooling/release-tools/blob/master/bloom/ros_gz/README.md)
    - Clone branches and tags from a local ros2-gbp/ros_ign-release checkout
     - `git remote add gzharmonic git@github.com:gazebo-release/ros_gz-gzharmonic-release.git && git push --all 
gzharmonic && git push --tags gzharmonic`
    - Rename bloom metadata
       - `GZ_RELEASE_TO_CONFLICT=garden ./release-tools/bloom/ros_gz/rename-ros_gz-pkgs.bash harmonic iron`
     - Modify tracks https://github.com/gazebo-release/ros_gz-gzharmonic-release/commit/6f7cd8df58677f4d59a8e1693c52558357aa952a
 - [x] Release into stable 
   - ```RELEASE_REPO_URL=https://github.com/gazebo-release/ros_gz-gzharmonic-release \
       ./bloom_from_special_env.bash \
          iron \
          harmonic \
       https://raw.githubusercontent.com/osrf/osrf-rosdep/master/gz/replace_fortress_with_harmonic/00-replace-gz-fortress-with-harmonic.list```
   - ```./ros_gz-release.py.bash 0.246.0 https://github.com/gazebo-release/ros_gz-gzharmonic-release iron <token> -r 1```
 - [x] DSL support for testing Iron GzHarmonic
   - [x] https://github.com/gazebo-tooling/release-tools/pull/1023
 
## Testing:
~~Install the [Gazebo prerelease](https://classic.gazebosim.org/tutorials?tut=install_unstable&cat=install#Gazeboprereleaserepo) repository~~
~~apt-get remove ros-iron-ros-gzgarden* # conflicting~~
apt-get update && apt-get install ros-iron-ros-gzharmonic

## Known problems:
~~There could be conflicts with `ros-iron-ros-gzgarden` packages.~~

**Comment by azeey** [comment]
I've tested both `ros-iron-ros-gzharmonic` and `ros-iron-ros-gzgarden` and they both seem to work well. As you mentioned, they do have a conflict:

<details><summary>dpkg error</summary>

```
dpkg: error processing archive /tmp/apt-dpkg-install-XbnKhE/0-ros-iron-ros-gzgarden-interfaces_0.245.0-1003jammy_amd64.deb (--unpack):
 trying to overwrite '/opt/ros/iron/include/ros_gz_interfaces/ros_gz_interfaces/msg/contact.h', which is also in package ros-iron-ros-gzharmonic-interfaces 0.246.0-2jammy
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package ros-iron-ros-gzgarden-bridge.
Preparing to unpack .../1-ros-iron-ros-gzgarden-bridge_0.245.0-1003jammy_amd64.deb ...
Unpacking ros-iron-ros-gzgarden-bridge (0.245.0-1003jammy) ...
dpkg: error processing archive /tmp/apt-dpkg-install-XbnKhE/1-ros-iron-ros-gzgarden-bridge_0.245.0-1003jammy_amd64.deb (--unpack):
 trying to overwrite '/opt/ros/iron/include/ros_gz_bridge/bridge_config.hpp', which is also in package ros-iron-ros-gzharmonic-bridge 0.246.0-2jammy
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package ros-iron-ros-gzgarden-image.
Preparing to unpack .../2-ros-iron-ros-gzgarden-image_0.245.0-1003jammy_amd64.deb ...
Unpacking ros-iron-ros-gzgarden-image (0.245.0-1003jammy) ...
dpkg: error processing archive /tmp/apt-dpkg-install-XbnKhE/2-ros-iron-ros-gzgarden-image_0.245.0-1003jammy_amd64.deb (--unpack):
 trying to overwrite '/opt/ros/iron/lib/ros_gz_image/image_bridge', which is also in package ros-iron-ros-gzharmonic-image 0.246.0-2jammy
Selecting previously unselected package ros-iron-ros-gzgarden-sim.
Preparing to unpack .../3-ros-iron-ros-gzgarden-sim_0.245.0-1003jammy_amd64.deb ...
Unpacking ros-iron-ros-gzgarden-sim (0.245.0-1003jammy) ...
dpkg: error processing archive /tmp/apt-dpkg-install-XbnKhE/3-ros-iron-ros-gzgarden-sim_0.245.0-1003jammy_amd64.deb (--unpack):
 trying to overwrite '/opt/ros/iron/include/ros_gz_sim/Stopwatch.hpp', which is also in package ros-iron-ros-gzharmonic-sim 0.246.0-2jammy
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package ros-iron-ros-gzgarden-sim-demos.
Preparing to unpack .../4-ros-iron-ros-gzgarden-sim-demos_0.245.0-1003jammy_amd64.deb ...
Unpacking ros-iron-ros-gzgarden-sim-demos (0.245.0-1003jammy) ...
dpkg: error processing archive /tmp/apt-dpkg-install-XbnKhE/4-ros-iron-ros-gzgarden-sim-demos_0.245.0-1003jammy_amd64.deb (--unpack):
 trying to overwrite '/opt/ros/iron/share/ament_index/resource_index/package_run_dependencies/ros_gz_sim_demos', which is also in package ros-iron-ros-gzharmonic-sim-demos 0.246.0-2jammy
Selecting previously unselected package ros-iron-ros-gzgarden.
Preparing to unpack .../5-ros-iron-ros-gzgarden_0.245.0-1003jammy_amd64.deb ...
Unpacking ros-iron-ros-gzgarden (0.245.0-1003jammy) ...
dpkg: error processing archive /tmp/apt-dpkg-install-XbnKhE/5-ros-iron-ros-gzgarden_0.245.0-1003jammy_amd64.deb (--unpack):
 trying to overwrite '/opt/ros/iron/share/ament_index/resource_index/package_run_dependencies/ros_gz', which is also in package ros-iron-ros-gzharmonic 0.246.0-2jammy
Errors were encountered while processing:
 /tmp/apt-dpkg-install-XbnKhE/0-ros-iron-ros-gzgarden-interfaces_0.245.0-1003jammy_amd64.deb
 /tmp/apt-dpkg-install-XbnKhE/1-ros-iron-ros-gzgarden-bridge_0.245.0-1003jammy_amd64.deb
 /tmp/apt-dpkg-install-XbnKhE/2-ros-iron-ros-gzgarden-image_0.245.0-1003jammy_amd64.deb
 /tmp/apt-dpkg-install-XbnKhE/3-ros-iron-ros-gzgarden-sim_0.245.0-1003jammy_amd64.deb
 /tmp/apt-dpkg-install-XbnKhE/4-ros-iron-ros-gzgarden-sim-demos_0.245.0-1003jammy_amd64.deb
 /tmp/apt-dpkg-install-XbnKhE/5-ros-iron-ros-gzgarden_0.245.0-1003jammy_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

</details>

I think it would be best if we declare the conflict in the package so users aren't faced with the scary error message from `dpkg`.

**Comment by j-rivero** [comment]
> I've tested both `ros-iron-ros-gzharmonic` and `ros-iron-ros-gzgarden` and they both seem to work well. As you mentioned, they do have a conflict:
> dpkg error
> 
> I think it would be best if we declare the conflict in the package so users aren't faced with the scary error message from `dpkg`.

In https://github.com/gazebo-tooling/release-tools/pull/1003 I've included the patch https://github.com/gazebo-tooling/release-tools/commit/def8aa189b8869f7cc1c5a8a8b29b48f1cecdf40 that should appear when we generate the stable version. Doing it for the existing repository was a bit more complicated.

**Comment by j-rivero** [comment]
Stable release out. All the documentation and CI in place.
